[simulation]
#Test case : 1 -> u_0 = 5.0, 2 -> heaviside entre 0.4 et 0.6
test_case = 2

#Solution Type
solutionType = "space"

#Number of dimensions
nbDims = 2

#Number of MC particles 
nbMC = 10000

#Final time of the simulation
finalTime = 1.0 

# Time step of the simulation
dt = 0.1

#Speed of the wanted result
v1 = 0.5
v2 = 0.5
v3 = 0.0

# Sizes of the domain
xmin = -1.0
xmax = 1.0
nbPtsX = 100
ymin = -1.0
ymax = 1.0
nbPtsY = 40
zmin = -1.0
zmax = 1.0
nbPtsZ = 30 

# Type of domain
domainType = "elastic"

[physics]
sigmaS = 0.0
sigmaT = 0.0
modV = 1.0